import { useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { CheckSquare, FileText, FolderOpen, GitBranch, LayoutList, Plus, Search, Sparkles, StickyNote, Workflow, X } from "lucide-react";
import { mockFiles, mockNotes, mockTasks, type Note } from "../../mock/notes";
import NeuroView from "../../components/notes/NeuroView/NeuroView";

type View = "notes" | "tasks" | "neuroview" | "neuroflow" | "neuropulse" | "files" | "notion";
const modules: Array<{ id: View; label: string; icon: typeof StickyNote }> = [
  { id: "notes", label: "Notas", icon: StickyNote }, { id: "tasks", label: "Tarefas", icon: CheckSquare }, { id: "neuroview", label: "NeuroView", icon: GitBranch }, { id: "neuroflow", label: "NeuroFlow", icon: Workflow }, { id: "neuropulse", label: "NeuroPulse", icon: Sparkles }, { id: "files", label: "Arquivos", icon: FolderOpen }, { id: "notion", label: "Notion", icon: LayoutList },
];
function Placeholder({ view }: { view: View }) { const config=modules.find(x=>x.id===view)!; const Icon=config.icon; return <div className="notes-module-placeholder"><div className="notes-module-icon"><Icon size={22}/></div><h2>{config.label}</h2><p>{view==='neuroflow'? 'Canvas de fluxos clínicos.' : view==='neuropulse' ? 'Diagramas e lentes clínicas.' : 'Superfície reservada para a próxima etapa.'}</p><span>Estrutura importada; implementação profunda será trazida em etapas.</span></div> }
function NoteEditor({ note, onClose }: { note: Note; onClose:()=>void }) { return <div className="notes-editor"><div className="notes-editor-head"><div><span>NOTA</span><h2>{note.title}</h2></div><button className="notes-icon-btn" onClick={onClose}><X size={16}/></button></div><div className="notes-editor-body"><p>{note.preview}</p><p>Conteúdo local do laboratório. Persistência real será integrada somente depois da validação visual.</p></div></div> }
export default function Notes(){
 const [view,setView]=useState<View>('notes'); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<Note|null>(mockNotes[0]); const [tasks,setTasks]=useState(mockTasks);
 const filtered=useMemo(()=>mockNotes.filter(n=>`${n.title} ${n.preview} ${n.tag}`.toLowerCase().includes(query.toLowerCase())),[query]);
 return <section className="notes-page"><div className="notes-shell"><aside className="notes-sidebar"><div className="notes-sidebar-head"><div><span>NEURONEX</span><strong>Workspace</strong></div><button className="notes-icon-btn"><Plus size={16}/></button></div><div className="notes-module-list">{modules.map(({id,label,icon:Icon})=><button key={id} className={view===id?'selected':''} onClick={()=>setView(id)}><Icon size={15}/><span>{label}</span></button>)}</div><div className="notes-sidebar-footer"><Sparkles size={14}/><span>Synapse pode navegar por este workspace.</span></div></aside><AnimatePresence mode="wait">
 {view==='notes' ? <motion.div key="notes" className="notes-main" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="notes-list-panel"><div className="notes-list-head"><div><span>NOTAS</span><h1>Minhas notas</h1></div><button className="primary-btn"><Plus size={14}/> Nova nota</button></div><div className="notes-search"><Search size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar notas..."/></div><div className="notes-list">{filtered.map(note=><button key={note.id} className={`note-row ${selected?.id===note.id?'selected':''}`} onClick={()=>setSelected(note)}><div className="note-row-top"><strong>{note.title}</strong><span>{note.updatedAt}</span></div><p>{note.preview}</p><small>{note.tag}</small></button>)}{!filtered.length&&<div className="notes-empty">Nenhuma nota encontrada.</div>}</div></div>{selected&&<NoteEditor note={selected} onClose={()=>setSelected(null)}/>}</motion.div>
 : view==='tasks' ? <motion.div key="tasks" className="notes-content-panel" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="notes-panel-title"><div><span>TAREFAS</span><h1>Quadro de tarefas</h1></div><button className="primary-btn"><Plus size={14}/> Nova tarefa</button></div><div className="task-board"><div className="task-column"><span>A FAZER</span>{tasks.filter(t=>!t.done).map(t=><button key={t.id} className="task-card" onClick={()=>setTasks(c=>c.map(x=>x.id===t.id?{...x,done:true}:x))}><CheckSquare size={14}/>{t.title}</button>)}</div><div className="task-column"><span>CONCLUÍDAS</span>{tasks.filter(t=>t.done).map(t=><button key={t.id} className="task-card done" onClick={()=>setTasks(c=>c.map(x=>x.id===t.id?{...x,done:false}:x))}><CheckSquare size={14}/>{t.title}</button>)}</div></div></motion.div>
 : view==='neuroview' ? <motion.div key="neuroview" className="notes-content-panel neuroview-panel" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><NeuroView/></motion.div>
 : view==='files' ? <motion.div key="files" className="notes-content-panel" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="notes-panel-title"><div><span>ARQUIVOS</span><h1>Documentos</h1></div><button className="primary-btn"><Plus size={14}/> Enviar arquivo</button></div><div className="file-grid">{mockFiles.map(f=><div className="file-card" key={f.id}><FileText size={20}/><strong>{f.name}</strong><span>{f.type} · {f.size}</span></div>)}</div></motion.div>
 : <motion.div key={view} className="notes-content-panel" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><Placeholder view={view}/></motion.div>}
 </AnimatePresence></div></section>
}